enable_mobile:
  IsConfig:   false

enable_pc:
  IsConfig:   false

invite_mode:
  IsConfig:   false

member_list_limit_for_simple_test:
  Name:      "member_list_limit_for_simple_test"
  Caption:   "プルダウンに表示するメンバーの最大値"
  FormType:  "input"
  ValueType: "int"
  IsConfig:   true
  IsRequired: true
  Default:    300
